name: macOS-virtual

on:
  workflow_dispatch:
  
jobs:
  macOS-virtual:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Query dependencies
        run: |
          install.packages(c('mapSpain', 'sf', 'readr', 'dplyr', 'glue', 'devtools', 'remotes'))
          install.packages(c('ggplot2', 'ggtext', 'ragg'))
          
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
          
          
            
      - name: Run script
        run: Rscript day01/day01_esp.R
        
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add day01
          git commit -m 'New map created' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
    
   
